include("testBICGSTB.jl")
include("testBlockBiCGSTB.jl")
include("testCG.jl")
include("testBlockCG.jl")
include("testCGLS.jl")
include("testGMRES.jl")
include("testLANCZOS.jl")
include("testSSOR.jl")
include("testLSQR.jl")
include("testMINRES.jl")
include("testMatrixDepot.jl")

